version: '3.8'

services:
  # Backend API
  api:
    build:
      context: .
      dockerfile: ./api.dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/against_wind
      - REDIS_URL=redis://redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=gpx-files
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - minio
    command: uv run uvicorn api.app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend UI
  ui:
    build:
      context: .
      dockerfile: ./ui.dockerfile
    ports:
      - "3100:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
    command: pnpm dev

  # Background worker
  worker:
    build:
      context: .
      dockerfile: ./api.dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/against_wind
      - REDIS_URL=redis://redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=gpx-files
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - minio
    command: uv run python -m api.app.worker.worker

  # Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=against_wind
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/migrations:/docker-entrypoint-initdb.d

  # Redis for caching and job queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  redis_data:
  minio_data:
